#!/bin/bash

if [ ! -f install ]; then
    echo 'install must be run within its container folder' 1>&2
    exit 1
fi

CURDIR=`pwd`
GOPATH=${CURDIR}
export GOPATH
go build -x -o gearman ./src/gearman/main.go
mv gearman ./bin

echo 'finished'